### ISSUE TITLE
steamVR inputs for a treadmill device broken with current release Vivecraft 1.12.2 v11

### ISSUE THREAD

**Issue by CybershoesVR** [jrbudda/Vivecraft_112#179]
Up until Vivecraft 1.12.2 v10 (Monsanto's finest release: r3 (7/29/2020)) all works well for the treadmills: Treadmill inputs (see binding file attached below) can be linked with game movement.

With release Vivecraft 1.12.2 v11 no more movement - same as with version Vivecraft 1.16.X

Vivecraft is quite popular among the Cybershoes community and **we hope that you @jrbudda :) accept a free Cybershoes kit** https://www.cybershoes.com/ in order to solve this. We already took a look but we do have no glue what went wrong. Also we suspect that this will affect all other treadmills/controllers that rely on steamVR input. 

Attaching our binding file (remove: .txt) and ingame settings:(https://github.com/jrbudda/Vivecraft_112/files/6686204/org.jrbudda.vivecraft.steamvrinput_cybershoes.json.txt)
![org jrbudda vivecraft steamvrinput](https://user-images.githubusercontent.com/42228867/122753876-2a802a00-d293-11eb-965b-00c6d0d2280d.jpg)

**Comment by Techjar** [comment]
I had a real good look at the changes that went into v11, but I just can't see anything that would mysteriously cause movement input exclusively from treadmills to not work. Can you also compare 1.16.1 v2 and 1.16.1 v3? It has some of the same changes.

**Comment by jrbudda** [comment]
I've looked as well and there is nothing obvious that would cause this issue. Can you give us a quick overview of how your app sends the input to the game? does this happen with all controller types (oculus, vive, index, etc)?

**Comment by CybershoesVR** [comment]
Thank you both for getting back to me (Michael). I think this is the crucial part of the binding file:

```
            {
               "inputs" : {
                  "position" : {
                     "output" : "/actions/ingame/in/vivecraft.key.freemovestrafe"
                  }
               },
               "mode" : "trackpad",
               "path" : "/user/treadmill/input/trackpad_default"        //<-this is the treadmill source: x,y float
            },
            {
               "inputs" : {
                  "click" : {
                     "output" : "/actions/ingame/in/key.jump"
                  }
               },
               "mode" : "button",
               "path" : "/user/treadmill/input/jump"                        //<-this is the treadmill source for jump: boolean
            }
```
also:
```
   "options" : {
      "returnBindingsWithLeftHand" : true
   },
```
Technically seen the Cybershoes are registered as a SteamVR controller with the role treadmill, called cybershoes. Joe Ludwig from Valve made it possible for treadmills to be "seen" by a game engine as a left hand controller (see the option returnBindingsWithLeftHand) , although the inputs come from the /user/treadmill path. 
Idea 1) Maybe this may cause an issue?

I noticed that once I do an initial joystick button press (Oculus) or trackpad button press (Vive), inputs **do** flow into the the game. Same with the 1.15.2 release. In other words, do one trackpad press on the Vive wand, keep the finger touched close to the middle, then a treadmill input bigger than the trackpad input is recognized by Vivecraft. You could even walk backwards on the treadmill. However, as soon as you stop, or let the finger go, any new input from the treadmill is not registered. 

Idea 2) Maybe Vivecraft ignores inputs unless the physical handcontroller is touched?

Idea 3) We did not properly link our treadmill touch with Vivecraft touch.
`"output" : "/actions/technical/in/vivecraft.key.trackpadtouch"` is not set by our treadmill.
I see this line in the bindings file **but** I cannot link it in the SteamVR input interface. There is no touch action I could bind it to. 

**QUESTION1**: do you wait for a touch event before letting the character walk? 
**QUESTION2**: do you match actions with physical controllers? If so I think the best solution would be to send you the Cybershoes.

Once again, we'd be happy to send you free Cybershoes in order to find our more, or just as a thank you for helping us out. Maybe send us your address to mail@cybershoes.com

**Comment by jrbudda** [comment]
OK that helps a lot. We do not require touch for analog movement to work so I do not think that is the problem unless it's something going on internal to SteamVR.

I'm concerned about that returnBindingsWithLeftHand setting. There is no documentation for it anywhere on the internet. We do not query freemovestrafe on a specific controller so that option should not be needed. Have you tried removing it? I'm not very confidant about this as a fix since this would not have changed between the versions you mentioned it stopped working, but worth a shot.

Also as a sanity check could you verify the behavior thus far with this version of Vivecraft? I've refactored some things and want to make sure I didn't accidently change the behavior and am looking at the code wrong. (change .zip to .exe)
[vivecraft-1.16.5-jrbudda-7-5-installer.zip](https://github.com/jrbudda/Vivecraft_112/files/6696341/vivecraft-1.16.5-jrbudda-7-5-installer.zip)

If we can't figure this out quickly you can send me the shoes and I will figure it out here, but I suspect it's something simple and we just need to get our finger on it.

**Comment by CybershoesVR** [comment]
Dear jrbudda, you fixed it!!! 🥇 I am so happy that this works now. You're such a great guy, please keep up the good work.  I tested it on Vive, Index, Rift, Quest Airlink and WMR. Also I verified again, the vivecraft-1.16.5-jrbudda-7-4-installer.exe has the issue but not the installer that you've sent me. Thank you so much, if you like to have the Cybershoes, welcome to drop us an email.

**Comment by jrbudda** [comment]
Yup, after uploading that test file I found what the problem was and realized that I did accidently bypass it.
Here are the 2 release candidates that have the full fix in place, if you want to give them a go and make sure all is well in both versions.
[vivecraft-1.12.2-jrbudda-11-r5-installer.zip](https://github.com/jrbudda/Vivecraft_112/files/6705308/vivecraft-1.12.2-jrbudda-11-r5-installer.zip)
[vivecraft-1.16.5-jrbudda-7-5-installer.zip](https://github.com/jrbudda/Vivecraft_112/files/6705310/vivecraft-1.16.5-jrbudda-7-5-installer.zip)

**Comment by CybershoesVR** [comment]
OK, something went wrong this time:

new 1.16 > error exit 0
[v1.16 with Rift SteamVR-2021-06-24-AM_11_07_44.txt](https://github.com/jrbudda/Vivecraft_112/files/6708061/v1.16.with.Rift.SteamVR-2021-06-24-AM_11_07_44.txt)

new 1.12 > null pointer error
[v1.12 with Rift SteamVR-2021-06-24-AM_11_14_27.txt](https://github.com/jrbudda/Vivecraft_112/files/6708063/v1.12.with.Rift.SteamVR-2021-06-24-AM_11_14_27.txt)
[v1.12 crash-2021-06-24_11.13.16-client.txt](https://github.com/jrbudda/Vivecraft_112/files/6708067/v1.12.crash-2021-06-24_11.13.16-client.txt)

previously working build: same thing

**re-installed previously working build and switched to INDEX:
WORKING AGAIN**  started previously installed new v1.16: works.

**reinstall new v1.16 (while steamVR running):** 
with INDEX without Cybershoes:
**same crash as in the beginning**
[reinstalled v116 with INDEX SteamVR-2021-06-24-AM_11_43_13.txt](https://github.com/jrbudda/Vivecraft_112/files/6708147/reinstalled.v116.with.INDEX.SteamVR-2021-06-24-AM_11_43_13.txt)
[reinstalled v1.16 crash-2021-06-24_11.42.23-client.txt](https://github.com/jrbudda/Vivecraft_112/files/6708140/reinstalled.v1.16.crash-2021-06-24_11.42.23-client.txt)

**Comment by Techjar** [comment]
Thanks, fixed for the next build.

**Comment by jrbudda** [comment]
See that's why we test these things :)

let's try again.

[vivecraft-1.16.5-jrbudda-7-5-installer.zip](https://github.com/jrbudda/Vivecraft_112/files/6711475/vivecraft-1.16.5-jrbudda-7-5-installer.zip)
[vivecraft-1.12.2-jrbudda-11-r5-installer.zip](https://github.com/jrbudda/Vivecraft_112/files/6711478/vivecraft-1.12.2-jrbudda-11-r5-installer.zip)

**Comment by CybershoesVR** [comment]
perfect. Thank you for the release. Feels now very responsive.
