### ISSUE TITLE
Can't install Vivecraft 1.12.1 on ubuntu

### ISSUE THREAD

**Issue by Galluno** [jrbudda/Vivecraft_112#192]
Hi, as for the title, no one can play vivecraft 1.12 on ubuntu, as on the release page there are only .exe files for VR type installers.
I see that the latest release has a .jar for the non-vr version, maybe future versions could be released as .jar, seeing that it is multiplatform?
Thank you

**Comment by TheTrueForce** [comment]
The reason vivecraft is shipped as exe installers is so that people don't try to install it as if it's a Forge mod and then complain when it doesn't work.
The installer is in fact a jar. It's just been run through a tool called Launch4J, that makes it a valid exe, and so that it starts the jar part when the exe bit is run.
As revealed in the FAQ, rename the .exe to a .jar, and run that.

**Comment by Galluno** [comment]
I didnt read the faq beforehand, whoops, sorry! 
Closing the issue now
