### ISSUE TITLE
[Mod incompatibility] Crash with Galacticraft

### ISSUE THREAD

**Issue by fayer3** [jrbudda/Vivecraft_112#63]
When trying to load a level with Galacticraft the game crashes with this error: 

java.lang.NoClassDefFoundError: micdoodle8/mods/galacticraft/core/entities/player/GCEntityPlayerMP

using: 
vivecraft 1.12.2 7 r4
galacticraft 1.12.2-4.0.1.181

crash report: https://gist.github.com/fayer3/5f994a06140ddda3ce6b0c82b67122e7
latest log: https://gist.github.com/fayer3/ea1cd34ceb05b662c9c6a2e7c8b8ac73

**Comment by Teslapirate** [comment]
This issue is still present in vivecraft-1.12.2-jrbudda-7-r6
using:
forge-1.12.2-14.23.5.2768
MicdoodleCore-1.12.2-4.0.1.181
GalacticraftCore-1.12.2-4.0.1.181

Crash report: https://gist.github.com/Teslapirate/866b7fe67be9b8c9ad6b4b7af512f75b
Logfile: https://gist.github.com/Teslapirate/47d756288fb34cc99589e52f01338c43

**Comment by jrbudda** [comment]
Galacticcraft 4 is listed as compatible now if you change some settings

>ViveCraft is compatible with Galacticraft, but it needs you to set a config setting: "Disable Vehicle Third-Person and Zoom"=true

**Comment by sackboy338** [comment]
> Galacticcraft 4 is listed as compatible now if you change some settings
> 
> > ViveCraft is compatible with Galacticraft, but it needs you to set a config setting: "Disable Vehicle Third-Person and Zoom"=true

I adjusted these settings accordingly, but I still crash with the exact same error. I've made absolutely certain that the setting is set to "true" several times. I'm not sure what the issue is. MC version: 1.12.2

Crash log:
[crash-2019-04-27_20.05.44-client.txt](https://github.com/jrbudda/Vivecraft_112/files/3124517/crash-2019-04-27_20.05.44-client.txt)

**Comment by jrbudda** [comment]
Ok reopening because despite the wiki, the crash does still occur.
I've been looking into this for the past couple hours now. It's pretty clearly an ASM incompatibility because if I disable micdoodle8.mods.miccore.MicdoodleTransformer the crash does not occur.  Somehow the galacticcraft coremod is breaking their own player entity classes without the ASM itself throwing an error.  Their player classes extend vanilla player classes so I'm guessing that's the root of the issue.

There's some overlap in the classes modified by both vivecraft and galacticcraft but none of them are directly tied to play entities.

This is a convoluted way of saying I have no idea what's wrong. I'm gonna have to individually jump out their patchers class by class until the problem goes away which will tell me which patcher is causing the problem, then see if I can remedy the asm conflict.

**Comment by sackboy338** [comment]
> Ok reopening because despite the wiki, the crash does still occur.
> I've been looking into this for the past couple hours now. It's pretty clearly an ASM incompatibility because if I disable micdoodle8.mods.miccore.MicdoodleTransformer the crash does not occur. Somehow the galacticcraft coremod is breaking their own player entity classes without the ASM itself throwing an error. Their player classes extend vanilla player classes so I'm guessing that's the root of the issue.
> 
> There's some overlap in the classes modified by both vivecraft and galacticcraft but none of them are directly tied to play entities.
> 
> This is a convoluted way of saying I have no idea what's wrong. I'm gonna have to individually jump out their patchers class by class until the problem goes away which will tell me which patcher is causing the problem, then see if I can remedy the asm conflict.

If you find a fix for the issue, it will be very much appreciated! :D

**Comment by jrbudda** [comment]
this is fixed i think
